<Project Sdk="Microsoft.NET.Sdk">
    <Import Project="../build.props" />
    <PropertyGroup>
        <TargetFramework>net7.0</TargetFramework>
        <ImplicitUsings>enable</ImplicitUsings>
        <Nullable>enable</Nullable>
        <LangVersion>default</LangVersion>
        <AllowUnsafeBlocks>true</AllowUnsafeBlocks>
        <AssemblyVersion>$(InteropVersion)</AssemblyVersion>
    </PropertyGroup>

    <ItemGroup>
      <PackageReference Include="System.Runtime.CompilerServices.Unsafe" Version="6.0.0" />
    </ItemGroup>
    
    <PropertyGroup>
        <_box2dlocation>..\Box2D.Native\bin\$(Configuration)\native\bin\$(Configuration)</_box2dlocation>
    </PropertyGroup>

    <ItemGroup Condition="Exists('$(_box2dlocation)\box2d.dll')">
        <Content Include="$(_box2dlocation)\box2d.dll">
            <Link>runtimes/win-x64/native/box2d.dll</Link>
            <PackagePath>lib/runtimes/win-x64/native/box2d.dll</PackagePath>
            <CopyToOutputDirectory>PreserveNewest</CopyToOutputDirectory>
            <Pack>true</Pack>
        </Content>
    </ItemGroup>

    <ItemGroup Condition="Exists('..\Box2D.Native\bin\$(Configuration)\native\src\libbox2d.so.3.0.0')">
        <Content Include="..\Box2D.Native\bin\$(Configuration)\native\src\libbox2d.so.3.0.0">
            <Link>runtimes/linux-x64/native/libbox2d.so</Link>
            <PackagePath>lib/runtimes/linux-x64/native/libbox2d.so</PackagePath>
            <CopyToOutputDirectory>PreserveNewest</CopyToOutputDirectory>
            <Pack>true</Pack>
        </Content>
    </ItemGroup>
</Project>
